/* compilador.java */
/* Generated By:JavaCC: Do not edit this line. compilador.java */
package proyecto1compi2;


import java.io.StringReader;
import java.util.ArrayList;

class compilador implements compiladorConstants {
        int contador=0;
        NodoArbol root = new NodoArbol();
        public String getEtiqueta(){

                contador++;
                String etiqueta="nodo"+contador;

                return etiqueta;
        }

        public void analizar(String cadena)  throws ParseException {

                try
                {
                        compilador analizador = new compilador(new StringReader(cadena) ) ;

                        root = analizador.iniciar();
                        System.out.println("SE ANALIZO CORRECTAMENTE ");
                }
                catch(ParseException e)
                {
                        System.out.println(e.getMessage());
                        System.out.println("Analizador: Se han encontrado errores en el analisis.");
                }

        }
        public compilador(){}

  final public NodoArbol iniciar() throws ParseException {NodoArbol nodo = new NodoArbol();
         nodo.nombre = "Ini"; nodo.grafoname=getEtiqueta(); nodo.cadena = "Ini"; nodo.numero =0;
    S();
{if ("" != null) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public void S() throws ParseException {
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case comentario:
      case comentarioall:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      COMENTARIOS();
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case publico:
    case privado:
    case protegido:{
      VISI();
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      ;
    }
    jj_consume_token(lienzo);
    jj_consume_token(id);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case extiende:{
      EXT();
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      ;
    }
    jj_consume_token(sigabrir);
    SENTENCIAS();
    jj_consume_token(sigcerrar);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case comentario:
      case comentarioall:{
        ;
        break;
        }
      default:
        jj_la1[3] = jj_gen;
        break label_2;
      }
      COMENTARIOS();
    }
    jj_consume_token(0);
  }

  final public void COMENTARIOS() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case comentario:{
      jj_consume_token(comentario);
      break;
      }
    case comentarioall:{
      jj_consume_token(comentarioall);
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void VISI() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case publico:{
      jj_consume_token(publico);
      break;
      }
    case privado:{
      jj_consume_token(privado);
      break;
      }
    case protegido:{
      jj_consume_token(protegido);
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void EXT() throws ParseException {
    jj_consume_token(extiende);
    jj_consume_token(id);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case coma:{
      EXT1();
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      ;
    }
  }

  final public void EXT1() throws ParseException {
    jj_consume_token(coma);
    jj_consume_token(id);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case coma:{
      EXT1();
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      ;
    }
  }

  final public void SENTENCIAS() throws ParseException {
    SEN();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case comentario:
    case comentarioall:
    case tentero:
    case tdoble:
    case tcaracter:
    case tboolean:
    case tcadena:
    case conservar:
    case publico:
    case privado:
    case protegido:
    case var:
    case si:
    case comprobar:
    case para:
    case mientras:
    case hacer:
    case continuar:
    case tvoid:
    case pintarP:
    case pintarOR:
    case pintarS:
    case principal:
    case id:{
      SENTENCIAS();
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      ;
    }
  }

  final public void SEN() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case comentario:{
      jj_consume_token(comentario);
      break;
      }
    case comentarioall:{
      jj_consume_token(comentarioall);
      break;
      }
    case tentero:
    case tdoble:
    case tcaracter:
    case tboolean:
    case tcadena:
    case conservar:
    case publico:
    case privado:
    case protegido:
    case var:
    case tvoid:
    case id:{
      CONTENIDO();
      break;
      }
    case si:{
      SENSI();
      break;
      }
    case comprobar:{
      SENCOMPROBAR();
      break;
      }
    case para:{
      SENPARA();
      break;
      }
    case mientras:{
      SENMIENTRAS();
      break;
      }
    case hacer:{
      SENHACER();
      break;
      }
    case continuar:{
      SENCONTINUAR();
      break;
      }
    case pintarP:{
      DIBUJAR_P();
      break;
      }
    case pintarOR:{
      DIBUJAR_OR();
      break;
      }
    case pintarS:{
      DIBUJAR_S();
      break;
      }
    case principal:{
      PRI();
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

//----------------------------------------------ACA ME QUEDE FECHA 26/08/2016
  final public void CONTENIDO() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case conservar:{
      CONSERV();
      break;
      }
    default:
      jj_la1[10] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case publico:
    case privado:
    case protegido:{
      VISI();
      break;
      }
    default:
      jj_la1[11] = jj_gen;
      ;
    }
    CONT();
  }

  final public void CONSERV() throws ParseException {
    jj_consume_token(conservar);
  }

  final public void CONT() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case var:{
      DECLARACION();
      break;
      }
    case tentero:
    case tdoble:
    case tcaracter:
    case tboolean:
    case tcadena:
    case tvoid:
    case id:{
      CONTENIDO3();
      break;
      }
    default:
      jj_la1[12] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void DECLARACION() throws ParseException {
    jj_consume_token(var);
    TIPO();
    VARIABLE();
  }

  final public void TIPO() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case tentero:{
      jj_consume_token(tentero);
      break;
      }
    case tdoble:{
      jj_consume_token(tdoble);
      break;
      }
    case tboolean:{
      jj_consume_token(tboolean);
      break;
      }
    case tcaracter:{
      jj_consume_token(tcaracter);
      break;
      }
    case tcadena:{
      jj_consume_token(tcadena);
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void VARIABLE() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case id:{
      NOMBRES();
      jj_consume_token(dolar);
      break;
      }
    case arreglo:{
      jj_consume_token(arreglo);
      break;
      }
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void NOMBRES() throws ParseException {
    jj_consume_token(id);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case igual:{
      ASIGN();
      break;
      }
    default:
      jj_la1[15] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case coma:{
      NOM();
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      ;
    }
  }

  final public void NOM() throws ParseException {
    jj_consume_token(coma);
    jj_consume_token(id);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case igual:{
      ASIGN();
      break;
      }
    default:
      jj_la1[17] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case coma:{
      NOM();
      break;
      }
    default:
      jj_la1[18] = jj_gen;
      ;
    }
  }

  final public void ASIGN() throws ParseException {
    jj_consume_token(igual);
    VALOR();
  }

  final public void VALOR() throws ParseException {
    C();
  }

  final public void CONT2() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case aumento:{
      jj_consume_token(aumento);
      break;
      }
    case decremento:{
      jj_consume_token(decremento);
      break;
      }
    case sumasim:{
      jj_consume_token(sumasim);
      VALOR();
      break;
      }
    case restasim:{
      jj_consume_token(restasim);
      VALOR();
      break;
      }
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

//----------------CALCULADORA
  final public void C() throws ParseException {
    E();
  }

  final public void E() throws ParseException {
    T();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case mas:
    case menos:{
      EP();
      break;
      }
    default:
      jj_la1[20] = jj_gen;
      ;
    }
  }

  final public void EP() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case mas:{
      jj_consume_token(mas);
      T();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case mas:
      case menos:{
        EP();
        break;
        }
      default:
        jj_la1[21] = jj_gen;
        ;
      }
      break;
      }
    case menos:{
      jj_consume_token(menos);
      T();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case mas:
      case menos:{
        EP();
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        ;
      }
      break;
      }
    default:
      jj_la1[23] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void T() throws ParseException {
    F();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case por:
    case div:{
      TP();
      break;
      }
    default:
      jj_la1[24] = jj_gen;
      ;
    }
  }

  final public void TP() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case por:{
      jj_consume_token(por);
      F();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case por:
      case div:{
        TP();
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        ;
      }
      break;
      }
    case div:{
      jj_consume_token(div);
      F();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case por:
      case div:{
        TP();
        break;
        }
      default:
        jj_la1[26] = jj_gen;
        ;
      }
      break;
      }
    default:
      jj_la1[27] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void F() throws ParseException {
    G();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case potencia:{
      FP();
      break;
      }
    default:
      jj_la1[28] = jj_gen;
      ;
    }
  }

  final public void FP() throws ParseException {
    jj_consume_token(potencia);
    G();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case potencia:{
      FP();
      break;
      }
    default:
      jj_la1[29] = jj_gen;
      ;
    }
  }

  final public void G() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case entero:{
      jj_consume_token(entero);
      break;
      }
    case doble:{
      jj_consume_token(doble);
      break;
      }
    case booleano:{
      jj_consume_token(booleano);
      break;
      }
    case caracter:{
      jj_consume_token(caracter);
      break;
      }
    case cadena:{
      jj_consume_token(cadena);
      break;
      }
    case id:{
      jj_consume_token(id);
      break;
      }
    case parenti:{
      jj_consume_token(parenti);
      E();
      jj_consume_token(parentd);
      break;
      }
    default:
      jj_la1[30] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

//-----------------RELACIONAL
  final public void RELACIONAL() throws ParseException {
    A();
  }

  final public void A() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case entero:
    case doble:
    case booleano:
    case caracter:
    case cadena:
    case parenti:
    case id:{
      EXP();
      REL();
      break;
      }
    case nulo:{
      jj_consume_token(nulo);
      EXP();
      break;
      }
    default:
      jj_la1[31] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void REL() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case igualacion:{
      jj_consume_token(igualacion);
      EXP();
      break;
      }
    case diferenciacion:{
      jj_consume_token(diferenciacion);
      EXP();
      break;
      }
    case menorque:{
      jj_consume_token(menorque);
      EXP();
      break;
      }
    case menorigualque:{
      jj_consume_token(menorigualque);
      EXP();
      break;
      }
    case mayorque:{
      jj_consume_token(mayorque);
      EXP();
      break;
      }
    case mayorigualque:{
      jj_consume_token(mayorigualque);
      EXP();
      break;
      }
    default:
      jj_la1[32] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void EXP() throws ParseException {
    E();
  }

//-------------------LOGICA
  final public void LOGICA() throws ParseException {
    L();
  }

  final public void L() throws ParseException {
    M();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case or:
    case nor:
    case xor:{
      LP();
      break;
      }
    default:
      jj_la1[33] = jj_gen;
      ;
    }
  }

  final public void LP() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case or:{
      jj_consume_token(or);
      M();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case or:
      case nor:
      case xor:{
        LP();
        break;
        }
      default:
        jj_la1[34] = jj_gen;
        ;
      }
      break;
      }
    case nor:{
      jj_consume_token(nor);
      M();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case or:
      case nor:
      case xor:{
        LP();
        break;
        }
      default:
        jj_la1[35] = jj_gen;
        ;
      }
      break;
      }
    case xor:{
      jj_consume_token(xor);
      M();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case or:
      case nor:
      case xor:{
        LP();
        break;
        }
      default:
        jj_la1[36] = jj_gen;
        ;
      }
      break;
      }
    default:
      jj_la1[37] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void M() throws ParseException {
    N();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case and:
    case nand:{
      MP();
      break;
      }
    default:
      jj_la1[38] = jj_gen;
      ;
    }
  }

  final public void MP() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case and:{
      jj_consume_token(and);
      N();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case and:
      case nand:{
        MP();
        break;
        }
      default:
        jj_la1[39] = jj_gen;
        ;
      }
      break;
      }
    case nand:{
      jj_consume_token(nand);
      N();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case and:
      case nand:{
        MP();
        break;
        }
      default:
        jj_la1[40] = jj_gen;
        ;
      }
      break;
      }
    default:
      jj_la1[41] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void N() throws ParseException {
    jj_consume_token(not);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case entero:
    case doble:
    case booleano:
    case caracter:
    case cadena:
    case nulo:
    case parenti:
    case id:{
      R();
      break;
      }
    default:
      jj_la1[42] = jj_gen;
      ;
    }
  }

//LA PARTE DE DECLARACION NO SE HA COMPLETADO
//LA PARTE DEL CONT2 NO SE HA COMPLETADO
  final public 
void R() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case entero:
    case doble:
    case booleano:
    case caracter:
    case cadena:
    case parenti:
    case id:{
      E();
      break;
      }
    case nulo:{
      RELACIONAL();
      break;
      }
    default:
      jj_la1[43] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

//SENTENCIAS DE CONTROL
  final public void SENSI() throws ParseException {
    jj_consume_token(si);
    jj_consume_token(parenti);
    LOGICA();
    jj_consume_token(parentd);
    jj_consume_token(sigabrir);
    SENTENCIAS();
    jj_consume_token(sigcerrar);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case sino:{
      SENSINO();
      break;
      }
    default:
      jj_la1[44] = jj_gen;
      ;
    }
  }

  final public void SENSINO() throws ParseException {
    jj_consume_token(sino);
    jj_consume_token(sigabrir);
    SENTENCIAS();
    jj_consume_token(sigcerrar);
  }

  final public void SENCOMPROBAR() throws ParseException {
    jj_consume_token(comprobar);
    jj_consume_token(parenti);
    jj_consume_token(id);
    jj_consume_token(parenti);
    jj_consume_token(parentd);
    jj_consume_token(sigabrir);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case caso:{
      CUERPO();
      break;
      }
    default:
      jj_la1[45] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case defecto:{
      DEFE();
      break;
      }
    default:
      jj_la1[46] = jj_gen;
      ;
    }
    jj_consume_token(sigcerrar);
  }

  final public void CUERPO() throws ParseException {
    jj_consume_token(caso);
    jj_consume_token(tvalor);
    jj_consume_token(entero);
    jj_consume_token(dospuntos);
    SENTENCIAS();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case salir:{
      SENSALIR();
      break;
      }
    default:
      jj_la1[47] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case caso:{
      CUERPO();
      break;
      }
    default:
      jj_la1[48] = jj_gen;
      ;
    }
  }

  final public void SENSALIR() throws ParseException {
    jj_consume_token(salir);
    jj_consume_token(dolar);
  }

  final public void DEFE() throws ParseException {
    jj_consume_token(defecto);
    jj_consume_token(dospuntos);
    SENTENCIAS();
  }

  final public void SENPARA() throws ParseException {
    jj_consume_token(para);
    jj_consume_token(parenti);
    INIPARA();
    jj_consume_token(puntoycoma);
    LOGICA();
    jj_consume_token(puntoycoma);
    jj_consume_token(id);
    CONT2();
    jj_consume_token(parentd);
    jj_consume_token(sigabrir);
    SENTENCIAS();
    jj_consume_token(sigcerrar);
  }

  final public void INIPARA() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case var:{
      DECLARACION();
      break;
      }
    case id:{
      jj_consume_token(id);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case igual:{
        ASIGN();
        break;
        }
      default:
        jj_la1[49] = jj_gen;
        ;
      }
      break;
      }
    default:
      jj_la1[50] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void SENMIENTRAS() throws ParseException {
    jj_consume_token(mientras);
    jj_consume_token(parenti);
    LOGICA();
    jj_consume_token(parentd);
    jj_consume_token(sigabrir);
    SENTENCIAS();
    jj_consume_token(sigcerrar);
  }

  final public void SENHACER() throws ParseException {
    jj_consume_token(hacer);
    jj_consume_token(sigabrir);
    SENTENCIAS();
    jj_consume_token(sigcerrar);
    jj_consume_token(mientras);
    jj_consume_token(parenti);
    LOGICA();
    jj_consume_token(parentd);
    jj_consume_token(dolar);
  }

  final public void SENCONTINUAR() throws ParseException {
    jj_consume_token(continuar);
    jj_consume_token(dolar);
  }

  final public void CONTENIDO3() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case tentero:
    case tdoble:
    case tcaracter:
    case tboolean:
    case tcadena:
    case tvoid:{
      TIPOMETODO();
      break;
      }
    default:
      jj_la1[51] = jj_gen;
      ;
    }
    jj_consume_token(id);
    METODO();
  }

  final public void TIPOMETODO() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case tentero:{
      jj_consume_token(tentero);
      break;
      }
    case tdoble:{
      jj_consume_token(tdoble);
      break;
      }
    case tboolean:{
      jj_consume_token(tboolean);
      break;
      }
    case tcaracter:{
      jj_consume_token(tcaracter);
      break;
      }
    case tcadena:{
      jj_consume_token(tcadena);
      break;
      }
    case tvoid:{
      jj_consume_token(tvoid);
      break;
      }
    default:
      jj_la1[52] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void METODO() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case parenti:{
      jj_consume_token(parenti);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case tentero:
      case tdoble:
      case tcaracter:
      case tboolean:
      case tcadena:{
        PARAMETROS();
        break;
        }
      default:
        jj_la1[53] = jj_gen;
        ;
      }
      jj_consume_token(parentd);
      jj_consume_token(sigabrir);
      SENTENCIAS();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case retorna:{
        RETO();
        break;
        }
      default:
        jj_la1[54] = jj_gen;
        ;
      }
      jj_consume_token(sigcerrar);
      break;
      }
    case igual:{
      jj_consume_token(igual);
      VALOR();
      break;
      }
    case aumento:
    case decremento:
    case sumasim:
    case restasim:{
      CONT2();
      break;
      }
    default:
      jj_la1[55] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void RETO() throws ParseException {
    jj_consume_token(retorna);
    C();
  }

  final public void PARAMETROS() throws ParseException {
    TIPO();
    jj_consume_token(id);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case coma:{
      PARAP();
      break;
      }
    default:
      jj_la1[56] = jj_gen;
      ;
    }
  }

  final public void PARAP() throws ParseException {
    jj_consume_token(coma);
    TIPO();
    jj_consume_token(id);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case coma:{
      PARAP();
      break;
      }
    default:
      jj_la1[57] = jj_gen;
      ;
    }
  }

//----------------------METODOS NATIVOS DEL LENGUAJE
  final public 
void DIBUJAR_P() throws ParseException {
    jj_consume_token(pintarP);
    jj_consume_token(parenti);
    C();
    jj_consume_token(coma);
    C();
    jj_consume_token(coma);
    C();
    jj_consume_token(coma);
    C();
    jj_consume_token(parentd);
    jj_consume_token(dolar);
  }

  final public void DIBUJAR_OR() throws ParseException {
    jj_consume_token(pintarOR);
    jj_consume_token(parenti);
    C();
    jj_consume_token(coma);
    C();
    jj_consume_token(coma);
    C();
    jj_consume_token(coma);
    C();
    jj_consume_token(coma);
    C();
    jj_consume_token(coma);
    C();
    jj_consume_token(parentd);
    jj_consume_token(dolar);
  }

  final public void DIBUJAR_S() throws ParseException {
    jj_consume_token(pintarS);
    jj_consume_token(parenti);
    C();
    jj_consume_token(coma);
    C();
    jj_consume_token(coma);
    C();
    jj_consume_token(coma);
    C();
    jj_consume_token(parentd);
    jj_consume_token(dolar);
  }

  final public void PRI() throws ParseException {
    jj_consume_token(principal);
    jj_consume_token(parenti);
    jj_consume_token(parentd);
    jj_consume_token(sigabrir);
    SENTENCIAS();
    jj_consume_token(sigcerrar);
  }

  /** Generated Token Manager. */
  public compiladorTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[58];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x1800,0x0,0x0,0x1800,0x1800,0x0,0x0,0x0,0x1f1800,0x1f1800,0x0,0x0,0x1f0000,0x1f0000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x7c0,0x80007c0,0x7e00000,0x90000000,0x90000000,0x90000000,0x90000000,0x90000000,0x60000000,0x60000000,0x60000000,0x60000000,0x80007c0,0x80007c0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1f0000,0x1f0000,0x1f0000,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x7000,0x100,0x0,0x0,0x7000,0x400,0x400,0x2800f200,0x2800f200,0x200,0x7000,0x8000,0x0,0x100000,0x800,0x400,0x800,0x400,0xf0000,0xc,0xc,0xc,0xc,0x30,0x30,0x30,0x30,0x40,0x40,0x800000,0x800000,0x0,0x1,0x1,0x1,0x1,0x1,0x0,0x0,0x0,0x0,0x800000,0x800000,0x10000000,0x40000000,0x0,0x0,0x40000000,0x800,0x8000,0x0,0x0,0x0,0x0,0x8f0800,0x400,0x400,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x203de8,0x203de8,0x0,0x0,0x200100,0x0,0x200000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x200000,0x200000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x200000,0x200000,0x0,0x0,0x4,0x2,0x0,0x0,0x200000,0x100,0x100,0x0,0x200,0x0,0x0,0x0,};
   }

  /** Constructor with InputStream. */
  public compilador(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public compilador(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new compiladorTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 58; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 58; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public compilador(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new compiladorTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 58; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 58; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public compilador(compiladorTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 58; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(compiladorTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 58; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk_f() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[86];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 58; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 86; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
